#!/usr/bin/env python3

from __future__ import annotations
import ctypes as ct
from ctypes import (
    c_int, c_uint, c_ulong, c_long, c_short, c_char, c_char_p,
    c_void_p, c_float, c_ubyte,
    POINTER, byref, cast, CFUNCTYPE,
)
import math
import os
import sys
import time

VERSION = "20260605"

USAGE = """usage: pboomer [OPTIONS]
  -d, --delay <seconds: float>  delay execution of the program by provided <seconds>
  -h, --help                    show this help and exit
      --new-config [filepath]   generate a new default config at [filepath]
  -c, --config <filepath>       use config at <filepath>
  -V, --version                 show the current version and exit
  -w, --windowed                windowed mode instead of fullscreen"""


# X11 / GL CONSTANTS

# event types
KeyPress       = 2
KeyRelease     = 3
ButtonPress    = 4
ButtonRelease  = 5
MotionNotify   = 6
ClientMessage  = 33

# event masks
KeyPressMask        = 1 << 0
KeyReleaseMask      = 1 << 1
ButtonPressMask     = 1 << 2
ButtonReleaseMask   = 1 << 3
PointerMotionMask   = 1 << 6
ExposureMask        = 1 << 15
CWColormap          = 1 << 13
CWEventMask         = 1 << 11
CWOverrideRedirect  = 1 << 9
CWSaveUnder         = 1 << 10

# x11 misc
ZPixmap        = 2
AllPlanes      = 0xFFFFFFFF
RevertToParent = 2
CurrentTime    = 0
AllocNone      = 0
InputOutput    = 1
False_         = 0
True_          = 1

# glx attrs
GLX_RGBA           = 4
GLX_DEPTH_SIZE     = 12
GLX_DOUBLEBUFFER   = 5

# keysyms
XK_Escape  = 0xFF1B
XK_q       = 0x0071
XK_r       = 0x0072
XK_f       = 0x0066
XK_m       = 0x006D
XK_0       = 0x0030
XK_equal   = 0x003D
XK_minus   = 0x002D
XK_ControlMask = 0x04
XK_Button1     = 1
XK_Button4     = 4
XK_Button5     = 5

# opengl constants
GL_COLOR_BUFFER_BIT    = 0x00004000
GL_DEPTH_BUFFER_BIT    = 0x00000100
GL_TEXTURE_2D          = 0x0DE1
GL_RGB                 = 0x1907
GL_BGRA                = 0x80E1
GL_UNSIGNED_BYTE       = 0x1401
GL_NEAREST             = 0x2600
GL_LINEAR              = 0x2601
GL_CLAMP_TO_BORDER     = 0x812D
GL_TEXTURE_MIN_FILTER  = 0x2801
GL_TEXTURE_MAG_FILTER  = 0x2800
GL_TEXTURE_WRAP_S      = 0x2802
GL_TEXTURE_WRAP_T      = 0x2803
GL_ARRAY_BUFFER        = 0x8892
GL_ELEMENT_ARRAY_BUFFER = 0x8893
GL_STATIC_DRAW         = 0x88E4
GL_FLOAT               = 0x1406
GL_VERTEX_SHADER       = 0x8B31
GL_FRAGMENT_SHADER     = 0x8B30
GL_COMPILE_STATUS      = 0x8B81
GL_LINK_STATUS         = 0x8B82
GL_TEXTURE0            = 0x84C0
GL_TRIANGLES           = 0x0004
GL_UNSIGNED_INT        = 0x1405


# CTYPES STRUCT DEFINITIONS

class XVisualInfo(ct.Structure):
    _fields_ = [
        ("visual",        c_void_p),
        ("visualid",      c_ulong),
        ("screen",        c_int),
        ("depth",         c_int),
        ("class",         c_int),
        ("red_mask",      c_ulong),
        ("green_mask",    c_ulong),
        ("blue_mask",     c_ulong),
        ("colormap_size", c_int),
        ("bits_per_rgb",  c_int),
    ]


class XSetWindowAttributes(ct.Structure):
    _fields_ = [
        ("background_pixmap",      c_ulong),
        ("background_pixel",       c_ulong),
        ("border_pixmap",          c_ulong),
        ("border_pixel",           c_ulong),
        ("bit_gravity",            c_int),
        ("win_gravity",            c_int),
        ("backing_store",          c_int),
        ("backing_planes",         c_ulong),
        ("backing_pixel",          c_ulong),
        ("save_under",             c_int),
        ("event_mask",             c_long),
        ("do_not_propagate_mask",  c_long),
        ("override_redirect",      c_int),
        ("colormap",               c_ulong),
        ("cursor",                 c_ulong),
    ]


class XWindowAttributes(ct.Structure):
    _fields_ = [
        ("x",                     c_int),
        ("y",                     c_int),
        ("width",                 c_int),
        ("height",                c_int),
        ("border_width",          c_int),
        ("depth",                 c_int),
        ("visual",                c_void_p),
        ("root",                  c_ulong),
        ("class",                 c_int),
        ("bit_gravity",           c_int),
        ("win_gravity",           c_int),
        ("backing_store",         c_int),
        ("backing_planes",        c_ulong),
        ("backing_pixel",         c_ulong),
        ("save_under",            c_int),
        ("colormap",              c_ulong),
        ("map_installed",         c_int),
        ("map_state",             c_int),
        ("all_event_masks",       c_long),
        ("your_event_mask",       c_long),
        ("do_not_propagate_mask", c_long),
        ("override_redirect",     c_int),
        ("screen",                c_void_p),
    ]


class XImage(ct.Structure):
    _fields_ = [
        ("width",           c_int),
        ("height",          c_int),
        ("xoffset",         c_int),
        ("format",          c_int),
        ("data",            c_void_p),
        ("byte_order",      c_int),
        ("bitmap_unit",     c_int),
        ("bitmap_bit_order", c_int),
        ("bitmap_pad",      c_int),
        ("depth",           c_int),
        ("bytes_per_line",  c_int),
        ("bits_per_pixel",  c_int),
    ]


class XClassHint(ct.Structure):
    _fields_ = [
        ("res_name",  c_char_p),
        ("res_class", c_char_p),
    ]


class XKeyEvent(ct.Structure):
    _fields_ = [
        ("type",        c_int),
        ("serial",      c_ulong),
        ("send_event",  c_int),
        ("display",     c_void_p),
        ("window",      c_ulong),
        ("root",        c_ulong),
        ("subwindow",   c_ulong),
        ("time",        c_ulong),
        ("x",           c_int),
        ("y",           c_int),
        ("x_root",      c_int),
        ("y_root",      c_int),
        ("state",       c_uint),
        ("keycode",     c_uint),
        ("same_screen", c_int),
    ]


class XButtonEvent(ct.Structure):
    _fields_ = [
        ("type",        c_int),
        ("serial",      c_ulong),
        ("send_event",  c_int),
        ("display",     c_void_p),
        ("window",      c_ulong),
        ("root",        c_ulong),
        ("subwindow",   c_ulong),
        ("time",        c_ulong),
        ("x",           c_int),
        ("y",           c_int),
        ("x_root",      c_int),
        ("y_root",      c_int),
        ("state",       c_uint),
        ("button",      c_uint),
        ("same_screen", c_int),
    ]


class XMotionEvent(ct.Structure):
    _fields_ = [
        ("type",        c_int),
        ("serial",      c_ulong),
        ("send_event",  c_int),
        ("display",     c_void_p),
        ("window",      c_ulong),
        ("root",        c_ulong),
        ("subwindow",   c_ulong),
        ("time",        c_ulong),
        ("x",           c_int),
        ("y",           c_int),
        ("x_root",      c_int),
        ("y_root",      c_int),
        ("state",       c_uint),
        ("is_hint",     c_char),
        ("same_screen", c_int),
    ]


class _ClientData(ct.Union):
    _fields_ = [
        ("b", c_char * 20),
        ("s", c_short * 10),
        ("l", c_long * 5),
    ]


class XClientMessageEvent(ct.Structure):
    _fields_ = [
        ("type",         c_int),
        ("serial",       c_ulong),
        ("send_event",   c_int),
        ("display",      c_void_p),
        ("window",       c_ulong),
        ("message_type", c_ulong),
        ("format",       c_int),
        ("data",         _ClientData),
    ]


class XErrorEvent(ct.Structure):
    _fields_ = [
        ("type",         c_int),
        ("display",      c_void_p),
        ("resourceid",   c_ulong),
        ("serial",       c_ulong),
        ("error_code",   c_ubyte),
        ("request_code", c_ubyte),
        ("minor_code",   c_ubyte),
    ]


class XEvent(ct.Union):
    _fields_ = [
        ("type",    c_int),
        ("xkey",    XKeyEvent),
        ("xbutton", XButtonEvent),
        ("xmotion", XMotionEvent),
        ("xclient", XClientMessageEvent),
        ("_pad",    c_long * 24),
    ]


# SHARED LIBRARY LOADING

_x11  = ct.CDLL("libX11.so.6")
_xr   = ct.CDLL("libXrandr.so.2")
_libgl = ct.CDLL("libGL.so.1")


# X11 / XRANDR FUNCTION TYPING

_x11.XOpenDisplay.argtypes       = [c_char_p]
_x11.XOpenDisplay.restype        = c_void_p

_x11.XCloseDisplay.argtypes      = [c_void_p]
_x11.XCloseDisplay.restype       = c_int

_x11.XDefaultRootWindow.argtypes = [c_void_p]
_x11.XDefaultRootWindow.restype  = c_ulong

_x11.XGetWindowAttributes.argtypes = [c_void_p, c_ulong, POINTER(XWindowAttributes)]
_x11.XGetWindowAttributes.restype  = c_int

_x11.XCreateColormap.argtypes    = [c_void_p, c_ulong, c_void_p, c_int]
_x11.XCreateColormap.restype     = c_ulong

_x11.XCreateWindow.argtypes = [
    c_void_p, c_ulong, c_int, c_int,
    c_uint, c_uint, c_uint, c_int,
    c_uint, c_void_p, c_ulong,
    POINTER(XSetWindowAttributes),
]
_x11.XCreateWindow.restype = c_ulong

_x11.XMapWindow.argtypes         = [c_void_p, c_ulong]
_x11.XMapWindow.restype          = c_int

_x11.XDestroyWindow.argtypes     = [c_void_p, c_ulong]
_x11.XDestroyWindow.restype      = c_int

_x11.XStoreName.argtypes         = [c_void_p, c_ulong, c_char_p]
_x11.XStoreName.restype          = c_int

_x11.XSetClassHint.argtypes      = [c_void_p, c_ulong, POINTER(XClassHint)]
_x11.XSetClassHint.restype       = c_int

_x11.XInternAtom.argtypes        = [c_void_p, c_char_p, c_int]
_x11.XInternAtom.restype         = c_ulong

_x11.XSetWMProtocols.argtypes    = [c_void_p, c_ulong, POINTER(c_ulong), c_int]
_x11.XSetWMProtocols.restype     = c_int

_x11.XPending.argtypes           = [c_void_p]
_x11.XPending.restype            = c_int

_x11.XNextEvent.argtypes         = [c_void_p, POINTER(XEvent)]
_x11.XNextEvent.restype          = c_int

_x11.XQueryPointer.argtypes = [
    c_void_p, c_ulong,
    POINTER(c_ulong), POINTER(c_ulong),
    POINTER(c_int), POINTER(c_int),
    POINTER(c_int), POINTER(c_int),
    POINTER(c_uint),
]
_x11.XQueryPointer.restype = c_int

_x11.XGetInputFocus.argtypes = [c_void_p, POINTER(c_ulong), POINTER(c_int)]
_x11.XGetInputFocus.restype  = c_int

_x11.XSetInputFocus.argtypes = [c_void_p, c_ulong, c_int, c_ulong]
_x11.XSetInputFocus.restype  = c_int

_x11.XSync.argtypes              = [c_void_p, c_int]
_x11.XSync.restype               = c_int

_x11.XGetImage.argtypes = [
    c_void_p, c_ulong, c_int, c_int,
    c_uint, c_uint, c_ulong, c_int,
]
_x11.XGetImage.restype = POINTER(XImage)

_x11.XDestroyImage.argtypes      = [POINTER(XImage)]
_x11.XDestroyImage.restype       = c_int

_x11.XLookupKeysym.argtypes      = [POINTER(XKeyEvent), c_int]
_x11.XLookupKeysym.restype       = c_ulong

_x11.XFree.argtypes              = [c_void_p]
_x11.XFree.restype               = c_int

_x11.XGetErrorText.argtypes = [c_void_p, c_int, c_char_p, c_int]
_x11.XGetErrorText.restype  = c_int

_xr.XRRGetScreenInfo.argtypes    = [c_void_p, c_ulong]
_xr.XRRGetScreenInfo.restype     = c_void_p

_xr.XRRConfigCurrentRate.argtypes = [c_void_p]
_xr.XRRConfigCurrentRate.restype  = c_int

_xr.XRRFreeScreenConfigInfo.argtypes = [c_void_p]
_xr.XRRFreeScreenConfigInfo.restype  = None


# GL / GLX FUNCTION TYPING

_libgl.glXChooseVisual.argtypes  = [c_void_p, c_int, POINTER(c_int)]
_libgl.glXChooseVisual.restype   = POINTER(XVisualInfo)

_libgl.glXCreateContext.argtypes = [c_void_p, POINTER(XVisualInfo), c_void_p, c_int]
_libgl.glXCreateContext.restype  = c_void_p

_libgl.glXMakeCurrent.argtypes   = [c_void_p, c_ulong, c_void_p]
_libgl.glXMakeCurrent.restype    = c_int

_libgl.glXSwapBuffers.argtypes   = [c_void_p, c_ulong]
_libgl.glXSwapBuffers.restype    = None

_libgl.glXDestroyContext.argtypes = [c_void_p, c_void_p]
_libgl.glXDestroyContext.restype  = None

_libgl.glXQueryVersion.argtypes  = [c_void_p, POINTER(c_int), POINTER(c_int)]
_libgl.glXQueryVersion.restype   = c_int

# core GL 1.1
_libgl.glClearColor.argtypes     = [c_float, c_float, c_float, c_float]
_libgl.glClearColor.restype      = None

_libgl.glClear.argtypes          = [c_uint]
_libgl.glClear.restype           = None

_libgl.glViewport.argtypes       = [c_int, c_int, c_int, c_int]
_libgl.glViewport.restype        = None

_libgl.glFinish.argtypes         = []
_libgl.glFinish.restype          = None

_libgl.glEnable.argtypes         = [c_uint]
_libgl.glEnable.restype          = None

_libgl.glGetString.argtypes      = [c_uint]
_libgl.glGetString.restype       = c_char_p

_libgl.glGenTextures.argtypes    = [c_int, POINTER(c_uint)]
_libgl.glGenTextures.restype     = None

_libgl.glActiveTexture.argtypes  = [c_uint]
_libgl.glActiveTexture.restype   = None

_libgl.glBindTexture.argtypes    = [c_uint, c_uint]
_libgl.glBindTexture.restype     = None

_libgl.glTexImage2D.argtypes = [
    c_uint, c_int, c_int, c_int, c_int, c_int, c_uint, c_uint, c_void_p,
]
_libgl.glTexImage2D.restype = None

_libgl.glGenerateMipmap.argtypes = [c_uint]
_libgl.glGenerateMipmap.restype  = None

_libgl.glTexParameteri.argtypes  = [c_uint, c_uint, c_int]
_libgl.glTexParameteri.restype   = None

_libgl.glDeleteTextures.argtypes = [c_int, POINTER(c_uint)]
_libgl.glDeleteTextures.restype  = None

# GL 2.0+ (should be in libGL.so on modern Mesa)
_libgl.glCreateShader.argtypes   = [c_uint]
_libgl.glCreateShader.restype    = c_uint

_libgl.glShaderSource.argtypes   = [c_uint, c_int, POINTER(c_char_p), POINTER(c_int)]
_libgl.glShaderSource.restype    = None

_libgl.glCompileShader.argtypes  = [c_uint]
_libgl.glCompileShader.restype   = None

_libgl.glGetShaderiv.argtypes    = [c_uint, c_uint, POINTER(c_int)]
_libgl.glGetShaderiv.restype     = None

_libgl.glGetShaderInfoLog.argtypes = [c_uint, c_int, POINTER(c_int), c_char_p]
_libgl.glGetShaderInfoLog.restype  = None

_libgl.glDeleteShader.argtypes   = [c_uint]
_libgl.glDeleteShader.restype    = None

_libgl.glCreateProgram.argtypes  = []
_libgl.glCreateProgram.restype   = c_uint

_libgl.glAttachShader.argtypes   = [c_uint, c_uint]
_libgl.glAttachShader.restype    = None

_libgl.glLinkProgram.argtypes    = [c_uint]
_libgl.glLinkProgram.restype     = None

_libgl.glGetProgramiv.argtypes   = [c_uint, c_uint, POINTER(c_int)]
_libgl.glGetProgramiv.restype    = None

_libgl.glGetProgramInfoLog.argtypes = [c_uint, c_int, POINTER(c_int), c_char_p]
_libgl.glGetProgramInfoLog.restype  = None

_libgl.glDeleteProgram.argtypes  = [c_uint]
_libgl.glDeleteProgram.restype   = None

_libgl.glUseProgram.argtypes     = [c_uint]
_libgl.glUseProgram.restype      = None

_libgl.glGetUniformLocation.argtypes = [c_uint, c_char_p]
_libgl.glGetUniformLocation.restype  = c_int

_libgl.glUniform1i.argtypes      = [c_int, c_int]
_libgl.glUniform1i.restype       = None

_libgl.glUniform1f.argtypes      = [c_int, c_float]
_libgl.glUniform1f.restype       = None

_libgl.glUniform2f.argtypes      = [c_int, c_float, c_float]
_libgl.glUniform2f.restype       = None

_libgl.glGenVertexArrays.argtypes  = [c_int, POINTER(c_uint)]
_libgl.glGenVertexArrays.restype   = None

_libgl.glGenBuffers.argtypes     = [c_int, POINTER(c_uint)]
_libgl.glGenBuffers.restype      = None

_libgl.glBindVertexArray.argtypes = [c_uint]
_libgl.glBindVertexArray.restype  = None

_libgl.glBindBuffer.argtypes     = [c_uint, c_uint]
_libgl.glBindBuffer.restype      = None

_libgl.glBufferData.argtypes = [c_uint, c_long, c_void_p, c_uint]
_libgl.glBufferData.restype  = None

_libgl.glVertexAttribPointer.argtypes = [c_uint, c_int, c_uint, c_ubyte, c_int, c_void_p]
_libgl.glVertexAttribPointer.restype  = None

_libgl.glEnableVertexAttribArray.argtypes = [c_uint]
_libgl.glEnableVertexAttribArray.restype  = None

_libgl.glDrawElements.argtypes = [c_uint, c_int, c_uint, c_void_p]
_libgl.glDrawElements.restype  = None

_libgl.glDeleteVertexArrays.argtypes = [c_int, POINTER(c_uint)]
_libgl.glDeleteVertexArrays.restype  = None

_libgl.glDeleteBuffers.argtypes  = [c_int, POINTER(c_uint)]
_libgl.glDeleteBuffers.restype   = None


# X11 ERROR HANDLER

_XErrorHandlerType = CFUNCTYPE(c_int, c_void_p, POINTER(XErrorEvent))

@_XErrorHandlerType
def _x11_error_handler(display, error_ev_ptr):
    buf = ct.create_string_buffer(256)
    ev = error_ev_ptr.contents
    _x11.XGetErrorText(display, ev.error_code, buf, 256)
    msg = buf.value.decode("utf-8", errors="replace")
    print(f"error: x11: {msg}", file=sys.stderr)
    return 0

# keep a reference so the callback isnt garbage-collected
_x11_error_handler_ref = _x11_error_handler


# SHADER SOURCES

_vertex_shader_source = b"""#version 130
in vec3       aPos;
in vec2       aTexCoord;
out vec2      texcoord;
uniform vec2  camera_pos;
uniform float camera_scale;
uniform vec2  window_size;
uniform vec2  screenshot_size;
vec3 to_world(vec3 v) {
    vec2 ratio = vec2(
        window_size.x / screenshot_size.x / camera_scale,
        window_size.y / screenshot_size.y / camera_scale);
    return vec3((v.x / screenshot_size.x * 2.0 - 1.0) / ratio.x,
                (v.y / screenshot_size.y * 2.0 - 1.0) / ratio.y,
                v.z);
}
void main() {
    gl_Position = vec4(to_world((aPos - vec3(camera_pos * vec2(1.0, -1.0), 0.0))), 1.0);
    texcoord    = aTexCoord;
}
"""

_fragment_shader_source = b"""#version 130
out mediump vec4  color;
in mediump vec2   texcoord;
uniform sampler2D tex;
uniform vec2      cursor_pos;
uniform vec2      window_size;
uniform float     fl_shadow;
uniform float     fl_radius;
uniform float     camera_scale;
uniform float     fl_feather;
uniform float     mirror;
void main() {
    vec4 cursor = vec4(cursor_pos.x, window_size.y - cursor_pos.y, 0.0, 1.0);
    float dist = length(cursor - gl_FragCoord);
    float radius_px = fl_radius * camera_scale;
    float inner = radius_px * (1.0 - fl_feather);
    float outer = radius_px;
    float alpha = smoothstep(inner, outer, dist);
    vec2 tc = texcoord;
    if (mirror > 0.5) tc.x = 1.0 - tc.x;
    color = mix(texture(tex, tc), vec4(0.0, 0.0, 0.0, 0.0), alpha * fl_shadow);
}
"""


# CONFIG

class Config:
    __slots__ = (
        "min_scale", "scroll_speed", "drag_friction", "scale_friction",
        "velocity_threshold", "scale_change_threshold",
        "initial_radius", "initial_delta_radius", "radius_damping",
        "fade_speed", "max_shadow_opacity", "radius_change_threshold",
        "feather", "texture_filter",
        "key_escape", "key_flashlight", "key_reset", "key_mirror",
        "key_zoom_in", "key_zoom_out",
        "modifier_flashlight", "button_drag", "button_zoom_in", "button_zoom_out",
        "_keys",
    )

    def __init__(self):
        # camera
        self.min_scale = 0.5
        self.scroll_speed = 1.5
        self.drag_friction = 6.0
        self.scale_friction = 4.0
        self.velocity_threshold = 15.0
        self.scale_change_threshold = 0.5
        # flashlight
        self.initial_radius = 200.0
        self.initial_delta_radius = 250.0
        self.radius_damping = 10.0
        self.fade_speed = 6.0
        self.max_shadow_opacity = 0.8
        self.radius_change_threshold = 1.0
        self.feather = 0.0
        # opengl
        self.texture_filter = 0
        # key bindings
        self.key_escape = XK_Escape
        self.key_flashlight = XK_f
        self.key_reset = XK_0
        self.key_mirror = XK_m
        self.key_zoom_in = XK_equal
        self.key_zoom_out = XK_minus
        self.modifier_flashlight = XK_ControlMask
        self.button_drag = XK_Button1
        self.button_zoom_in = XK_Button4
        self.button_zoom_out = XK_Button5
        # parse map
        self._keys = {
            "min_scale": ("min_scale", float),
            "scroll_speed": ("scroll_speed", float),
            "drag_friction": ("drag_friction", float),
            "scale_friction": ("scale_friction", float),
            "velocity_threshold": ("velocity_threshold", float),
            "scale_change_threshold": ("scale_change_threshold", float),
            "initial_radius": ("initial_radius", float),
            "initial_delta_radius": ("initial_delta_radius", float),
            "radius_damping": ("radius_damping", float),
            "fade_speed": ("fade_speed", float),
            "max_shadow_opacity": ("max_shadow_opacity", float),
            "radius_change_threshold": ("radius_change_threshold", float),
            "feather": ("feather", float),
            "texture_filter": ("texture_filter", int),
        }

    def apply_value(self, key, val):
        entry = self._keys.get(key)
        if entry is None:
            return
        attr, typ = entry
        try:
            setattr(self, attr, typ(val))
        except (ValueError, TypeError):
            pass

    def load_from_file(self, path):
        try:
            with open(path) as f:
                for line in f:
                    stripped = line.strip()
                    if not stripped or stripped.startswith("#"):
                        continue
                    if "=" not in stripped:
                        continue
                    k, _, v = stripped.partition("=")
                    self.apply_value(k.strip(), v.strip())
        except FileNotFoundError:
            pass

    @staticmethod
    def write_default(path):
        c = Config()
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w") as f:
            f.write(f"min_scale = {c.min_scale:.1f}\n")
            f.write(f"scroll_speed = {c.scroll_speed:.1f}\n")
            f.write(f"drag_friction = {c.drag_friction:.1f}\n")
            f.write(f"scale_friction = {c.scale_friction:.1f}\n")
            f.write(f"velocity_threshold = {c.velocity_threshold:.1f}\n")
            f.write(f"scale_change_threshold = {c.scale_change_threshold:.2f}\n")
            f.write(f"initial_radius = {c.initial_radius:.1f}\n")
            f.write(f"initial_delta_radius = {c.initial_delta_radius:.1f}\n")
            f.write(f"radius_damping = {c.radius_damping:.1f}\n")
            f.write(f"fade_speed = {c.fade_speed:.1f}\n")
            f.write(f"max_shadow_opacity = {c.max_shadow_opacity:.2f}\n")
            f.write(f"radius_change_threshold = {c.radius_change_threshold:.2f}\n")
            f.write(f"feather = {c.feather:.2f}\n")
            f.write(f"texture_filter = {c.texture_filter}\n")

    @staticmethod
    def default_config_path():
        home = os.environ.get("HOME")
        if not home:
            return None
        return os.path.join(home, ".config", "boomer", "config")


# APPLICATION STATE

class Camera:
    __slots__ = ("position_x", "position_y", "velocity_x", "velocity_y",
                 "scale", "delta_scale", "scale_pivot_x", "scale_pivot_y")
    def __init__(self):
        self.position_x = 0.0
        self.position_y = 0.0
        self.velocity_x = 0.0
        self.velocity_y = 0.0
        self.scale = 1.0
        self.delta_scale = 0.0
        self.scale_pivot_x = 0.0
        self.scale_pivot_y = 0.0


class Mouse:
    __slots__ = ("curr_x", "curr_y", "prev_x", "prev_y", "drag")
    def __init__(self):
        self.curr_x = 0.0
        self.curr_y = 0.0
        self.prev_x = 0.0
        self.prev_y = 0.0
        self.drag = False


class Flashlight:
    __slots__ = ("enabled", "shadow", "radius", "delta_radius")
    def __init__(self):
        self.enabled = False
        self.shadow = 0.0
        self.radius = 0.0
        self.delta_radius = 0.0


class State:
    __slots__ = ("camera", "mouse", "flashlight", "dt", "running", "mirror")
    def __init__(self):
        self.camera = Camera()
        self.mouse = Mouse()
        self.flashlight = Flashlight()
        self.dt = 0.0
        self.running = True
        self.mirror = False


class App:
    __slots__ = ("config", "state", "config_path")

    def __init__(self, config, config_path=None):
        self.config = config
        self.state = State()
        self.config_path = config_path
        self.state.flashlight.radius = config.initial_radius
        if config_path:
            config.load_from_file(config_path)

    def camera_update(self, ww, wh):
        cfg = self.config
        cam = self.state.camera
        dt = self.state.dt

        if abs(cam.delta_scale) > cfg.scale_change_threshold:
            half_w = ww * 0.5
            half_h = wh * 0.5
            sub_x = cam.scale_pivot_x - half_w
            sub_y = cam.scale_pivot_y - half_h
            p0_x = sub_x / cam.scale
            p0_y = sub_y / cam.scale

            cam.scale += cam.delta_scale * dt
            if cam.scale < cfg.min_scale:
                cam.scale = cfg.min_scale

            p1_x = sub_x / cam.scale
            p1_y = sub_y / cam.scale
            cam.position_x += p0_x - p1_x
            cam.position_y += p0_y - p1_y
            cam.delta_scale -= cam.delta_scale * dt * cfg.scale_friction

        m = self.state.mouse
        if not m.drag:
            vx = cam.velocity_x
            vy = cam.velocity_y
            vlen = math.sqrt(vx * vx + vy * vy)
            if vlen > cfg.velocity_threshold:
                cam.position_x += vx * dt
                cam.position_y += vy * dt
                cam.velocity_x -= vx * dt * cfg.drag_friction
                cam.velocity_y -= vy * dt * cfg.drag_friction

    def flashlight_update(self):
        fl = self.state.flashlight
        dt = self.state.dt
        cfg = self.config

        if fl.enabled:
            fl.shadow = min(fl.shadow + cfg.fade_speed * dt, cfg.max_shadow_opacity)
        else:
            fl.shadow = max(fl.shadow - cfg.fade_speed * dt, 0.0)

        if abs(fl.delta_radius) > cfg.radius_change_threshold:
            fl.radius = max(0.0, fl.radius + fl.delta_radius * dt)
            fl.delta_radius -= fl.delta_radius * cfg.radius_damping * dt

    def _world_position(self, pos_x, pos_y, scale):
        return pos_x / scale, pos_y / scale

    def seed_mouse(self, wx, wy):
        self.state.mouse.curr_x = float(wx)
        self.state.mouse.curr_y = float(wy)
        self.state.mouse.prev_x = float(wx)
        self.state.mouse.prev_y = float(wy)

    def _handle_keypress(self, keysym):
        cfg = self.config
        if keysym == cfg.key_escape or keysym == XK_q:
            self.state.running = False
        elif keysym == XK_r:
            if self.config_path:
                cfg.load_from_file(self.config_path)
        elif keysym == cfg.key_flashlight:
            self.state.flashlight.enabled = not self.state.flashlight.enabled
        elif keysym == cfg.key_reset:
            self.state.camera = Camera()
            self.state.flashlight.shadow = 0.0
            self.state.flashlight.radius = cfg.initial_radius
            self.state.flashlight.delta_radius = 0.0
        elif keysym == cfg.key_mirror:
            self.state.mirror = not self.state.mirror
        elif keysym == cfg.key_zoom_in:
            self.state.camera.delta_scale += cfg.scroll_speed
            self.state.camera.scale_pivot_x = self.state.mouse.curr_x
            self.state.camera.scale_pivot_y = self.state.mouse.curr_y
        elif keysym == cfg.key_zoom_out:
            self.state.camera.delta_scale -= cfg.scroll_speed
            self.state.camera.scale_pivot_x = self.state.mouse.curr_x
            self.state.camera.scale_pivot_y = self.state.mouse.curr_y

    def _handle_mousemove(self, motion_ptr, refresh_rate):
        motion = motion_ptr.contents
        m = self.state.mouse
        m.curr_x = float(motion.x)
        m.curr_y = float(motion.y)

        if m.drag:
            cam = self.state.camera
            prev_x, prev_y = self._world_position(m.prev_x, m.prev_y, cam.scale)
            cur_x, cur_y = self._world_position(m.curr_x, m.curr_y, cam.scale)
            cam.position_x += prev_x - cur_x
            cam.position_y += prev_y - cur_y
            cam.velocity_x = (prev_x - cur_x) * refresh_rate
            cam.velocity_y = (prev_y - cur_y) * refresh_rate

        m.prev_x = m.curr_x
        m.prev_y = m.curr_y

    def _handle_buttonpress(self, button_ptr):
        be = button_ptr.contents
        cfg = self.config
        ctrl_pressed = (be.state & cfg.modifier_flashlight) != 0

        if be.button == cfg.button_drag:
            m = self.state.mouse
            m.prev_x = m.curr_x
            m.prev_y = m.curr_y
            m.drag = True
            cam = self.state.camera
            cam.velocity_x = 0.0
            cam.velocity_y = 0.0
        elif be.button == cfg.button_zoom_in:
            if ctrl_pressed and self.state.flashlight.enabled:
                self.state.flashlight.delta_radius += cfg.initial_delta_radius
            else:
                self.state.camera.delta_scale += cfg.scroll_speed
                self.state.camera.scale_pivot_x = self.state.mouse.curr_x
                self.state.camera.scale_pivot_y = self.state.mouse.curr_y
        elif be.button == cfg.button_zoom_out:
            if ctrl_pressed and self.state.flashlight.enabled:
                self.state.flashlight.delta_radius -= cfg.initial_delta_radius
            else:
                self.state.camera.delta_scale -= cfg.scroll_speed
                self.state.camera.scale_pivot_x = self.state.mouse.curr_x
                self.state.camera.scale_pivot_y = self.state.mouse.curr_y

    def _handle_buttonrelease(self, button_ptr):
        be = button_ptr.contents
        if be.button == self.config.button_drag:
            self.state.mouse.drag = False


# OPENGL HELPERS

def _compile_shader(shader_type, source):
    shader = _libgl.glCreateShader(shader_type)
    src = ct.c_char_p(source)
    srclen = c_int(len(source))
    _libgl.glShaderSource(shader, 1, byref(src), byref(srclen))
    _libgl.glCompileShader(shader)

    success = c_int()
    _libgl.glGetShaderiv(shader, GL_COMPILE_STATUS, byref(success))
    if not success.value:
        log = ct.create_string_buffer(512)
        _libgl.glGetShaderInfoLog(shader, 512, None, log)
        print(f"error: shader compile: {log.value.decode(errors='replace')}", file=sys.stderr)
    return shader


def _build_program():
    v = _compile_shader(GL_VERTEX_SHADER, _vertex_shader_source)
    f = _compile_shader(GL_FRAGMENT_SHADER, _fragment_shader_source)

    prog = _libgl.glCreateProgram()
    _libgl.glAttachShader(prog, v)
    _libgl.glAttachShader(prog, f)
    _libgl.glLinkProgram(prog)

    success = c_int()
    _libgl.glGetProgramiv(prog, GL_LINK_STATUS, byref(success))
    if not success.value:
        log = ct.create_string_buffer(512)
        _libgl.glGetProgramInfoLog(prog, 512, None, log)
        print(f"error: program link: {log.value.decode(errors='replace')}", file=sys.stderr)

    _libgl.glDeleteShader(v)
    _libgl.glDeleteShader(f)
    _libgl.glUseProgram(prog)
    _libgl.glUniform1i(_libgl.glGetUniformLocation(prog, b"tex"), 0)

    # cache uniform locations
    locs = {
        "camera_pos":      _libgl.glGetUniformLocation(prog, b"camera_pos"),
        "camera_scale":    _libgl.glGetUniformLocation(prog, b"camera_scale"),
        "window_size":     _libgl.glGetUniformLocation(prog, b"window_size"),
        "screenshot_size": _libgl.glGetUniformLocation(prog, b"screenshot_size"),
        "cursor_pos":      _libgl.glGetUniformLocation(prog, b"cursor_pos"),
        "fl_shadow":       _libgl.glGetUniformLocation(prog, b"fl_shadow"),
        "fl_radius":       _libgl.glGetUniformLocation(prog, b"fl_radius"),
        "fl_feather":      _libgl.glGetUniformLocation(prog, b"fl_feather"),
        "mirror":          _libgl.glGetUniformLocation(prog, b"mirror"),
    }
    return prog, locs


def _create_texture(img, texture_filter):
    tex = c_uint()
    _libgl.glGenTextures(1, byref(tex))
    _libgl.glActiveTexture(GL_TEXTURE0)
    _libgl.glBindTexture(GL_TEXTURE_2D, tex)
    _libgl.glTexImage2D(
        GL_TEXTURE_2D, 0, GL_RGB,
        img.width, img.height, 0,
        GL_BGRA, GL_UNSIGNED_BYTE, img.data,
    )
    _libgl.glGenerateMipmap(GL_TEXTURE_2D)

    if texture_filter != 0:
        _libgl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
        _libgl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR)
    else:
        _libgl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST)
        _libgl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST)

    _libgl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER)
    _libgl.glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER)
    return tex


def _create_geometry(width, height):
    w = float(width)
    h = float(height)
    vertices = (c_float * 20)(
        w, 0.0, 0.0, 1.0, 1.0,
        w, h,   0.0, 1.0, 0.0,
        0.0, h, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0,
    )
    indices = (c_uint * 6)(0, 1, 3, 1, 2, 3)

    vao = c_uint()
    vbo = c_uint()
    ebo = c_uint()
    _libgl.glGenVertexArrays(1, byref(vao))
    _libgl.glGenBuffers(1, byref(vbo))
    _libgl.glGenBuffers(1, byref(ebo))

    _libgl.glBindVertexArray(vao)
    _libgl.glBindBuffer(GL_ARRAY_BUFFER, vbo)
    _libgl.glBufferData(GL_ARRAY_BUFFER, ct.sizeof(vertices), vertices, GL_STATIC_DRAW)
    _libgl.glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ebo)
    _libgl.glBufferData(GL_ELEMENT_ARRAY_BUFFER, ct.sizeof(indices), indices, GL_STATIC_DRAW)

    stride = 5 * ct.sizeof(c_float)
    _libgl.glVertexAttribPointer(0, 3, GL_FLOAT, False_, stride, None)
    _libgl.glEnableVertexAttribArray(0)
    _libgl.glVertexAttribPointer(1, 2, GL_FLOAT, False_, stride, c_void_p(3 * ct.sizeof(c_float)))
    _libgl.glEnableVertexAttribArray(1)

    return vao, vbo, ebo


# MAIN

def main(argv=None):
    if argv is None:
        argv = sys.argv

    # cli parsing
    windowed = False
    delay_sec = 0.0
    config_path = None
    new_cfg_out = None

    i = 1
    argn = len(argv)
    while i < argn:
        arg = argv[i]
        if arg in ("-h", "--help"):
            print(USAGE)
            return
        elif arg in ("-V", "--version"):
            print(f"pboomer-{VERSION}")
            return
        elif arg in ("-w", "--windowed"):
            windowed = True
        elif arg in ("-d", "--delay"):
            i += 1
            if i >= argn:
                print(f"error: no value provided for {arg}", file=sys.stderr)
                print(USAGE)
                sys.exit(1)
            try:
                delay_sec = float(argv[i])
            except ValueError:
                print(f"error: invalid delay value: {argv[i]}", file=sys.stderr)
                sys.exit(1)
        elif arg in ("-c", "--config"):
            i += 1
            if i >= argn:
                print(f"error: no value provided for {arg}", file=sys.stderr)
                print(USAGE)
                sys.exit(1)
            config_path = argv[i]
        elif arg == "--new-config":
            if i + 1 < argn and not argv[i + 1].startswith("-"):
                i += 1
                new_cfg_out = argv[i]
            else:
                new_cfg_out = Config.default_config_path()
            if new_cfg_out:
                Config.write_default(new_cfg_out)
                print(f"generated config at {new_cfg_out}")
            return
        else:
            print(f"error: unknown flag `{arg}`", file=sys.stderr)
            print(USAGE)
            sys.exit(1)
        i += 1

    # delay
    if delay_sec > 0.0:
        time.sleep(delay_sec)

    # resolve config path
    if config_path is None:
        config_path = Config.default_config_path()

    if config_path:
        print(f"using config: {config_path}")

    # x11 init
    display = _x11.XOpenDisplay(None)
    if not display:
        print("error: failed to open display", file=sys.stderr)
        sys.exit(1)

    _x11.XSetErrorHandler(_x11_error_handler_ref)

    root = _x11.XDefaultRootWindow(display)
    root_attrs = XWindowAttributes()
    _x11.XGetWindowAttributes(display, root, byref(root_attrs))

    sc = _xr.XRRGetScreenInfo(display, root)
    refresh_rate = _xr.XRRConfigCurrentRate(sc)
    _xr.XRRFreeScreenConfigInfo(sc)
    if refresh_rate <= 0:
        refresh_rate = 60

    screen_w = root_attrs.width
    screen_h = root_attrs.height
    print(f"screen: {screen_w}x{screen_h} @ {refresh_rate}hz")

    # GLX check
    glx_major = c_int()
    glx_minor = c_int()
    if not _libgl.glXQueryVersion(display, byref(glx_major), byref(glx_minor)):
        print("error: glXQueryVersion failed", file=sys.stderr)
        sys.exit(1)
    if glx_major.value < 1 or (glx_major.value == 1 and glx_minor.value < 3):
        print("error: need GLX >= 1.3", file=sys.stderr)
        sys.exit(1)
    print(f"glx version: {glx_major.value}.{glx_minor.value}")

    # create window
    glx_attrs = (c_int * 5)(GLX_RGBA, GLX_DEPTH_SIZE, 24, GLX_DOUBLEBUFFER, 0)
    vi = _libgl.glXChooseVisual(display, 0, glx_attrs)
    if not vi:
        print("error: no appropriate visual found", file=sys.stderr)
        sys.exit(1)

    vi_info = vi.contents
    print(f"visual id: 0x{vi_info.visualid:x}")

    swa = XSetWindowAttributes()
    swa.colormap = _x11.XCreateColormap(display, root, vi_info.visual, AllocNone)
    swa.event_mask = (ButtonPressMask | ButtonReleaseMask | KeyPressMask |
                      KeyReleaseMask | PointerMotionMask | ExposureMask)
    mask = CWColormap | CWEventMask

    if not windowed:
        swa.override_redirect = 1
        swa.save_under = 1
        mask |= CWOverrideRedirect | CWSaveUnder

    window = _x11.XCreateWindow(
        display, root,
        0, 0, screen_w, screen_h, 0,
        vi_info.depth, InputOutput, vi_info.visual,
        mask, byref(swa),
    )

    _x11.XStoreName(display, window, b"pboomer")
    ch = XClassHint(b"pboomer", b"Pboomer")
    _x11.XSetClassHint(display, window, byref(ch))

    wm_delete_window = c_ulong(0)
    if windowed:
        wm_delete_window = c_ulong(_x11.XInternAtom(display, b"WM_DELETE_WINDOW", False_))
        _x11.XSetWMProtocols(display, window, byref(wm_delete_window), 1)

    _x11.XMapWindow(display, window)

    gl_ctx = _libgl.glXCreateContext(display, vi, None, True_)
    if not gl_ctx:
        print("error: failed to create glx context", file=sys.stderr)
        sys.exit(1)
    _libgl.glXMakeCurrent(display, window, gl_ctx)
    _x11.XFree(vi)

    original_focus = c_ulong()
    revert = c_int()
    _x11.XGetInputFocus(display, byref(original_focus), byref(revert))

    # screenshot
    img_ptr = _x11.XGetImage(display, root, 0, 0, screen_w, screen_h, AllPlanes, ZPixmap)
    if not img_ptr:
        print("error: failed to take screenshot", file=sys.stderr)
        sys.exit(1)
    img = img_ptr.contents
    print(f"screenshot: {img.width}x{img.height}")

    # opengl init
    _libgl.glEnable(GL_TEXTURE_2D)

    ov = _libgl.glGetString(0x1F02)
    gl_version = ov.decode() if ov else "unknown"
    print(f"opengl version: {gl_version}")

    program, uniform_locs = _build_program()

    # app init
    app = App(Config(), config_path)

    texture = _create_texture(img, app.config.texture_filter)
    vao, vbo, ebo = _create_geometry(img.width, img.height)

    # seed mouse position
    root_ret = c_ulong()
    child_ret = c_ulong()
    rx = c_int(); ry = c_int(); wx = c_int(); wy = c_int(); msk = c_uint()
    _x11.XQueryPointer(display, root,
                       byref(root_ret), byref(child_ret),
                       byref(rx), byref(ry), byref(wx), byref(wy), byref(msk))
    app.seed_mouse(wx.value, wy.value)

    dt = 1.0 / float(refresh_rate)
    app.state.dt = dt

    # main loop
    event = XEvent()
    wa = XWindowAttributes()
    gl = _libgl
    x = _x11

    # local bindings for speed
    _glUniform2f        = gl.glUniform2f
    _glUniform1f        = gl.glUniform1f
    _glClearColor       = gl.glClearColor
    _glClear            = gl.glClear
    _glUseProgram       = gl.glUseProgram
    _glBindTexture      = gl.glBindTexture
    _glBindVertexArray  = gl.glBindVertexArray
    _glDrawElements     = gl.glDrawElements
    _glXSwapBuffers     = gl.glXSwapBuffers
    _glFinish           = gl.glFinish
    _glViewport         = gl.glViewport
    _XPending           = x.XPending
    _XNextEvent         = x.XNextEvent
    _XLookupKeysym      = x.XLookupKeysym
    _XSetInputFocus     = x.XSetInputFocus

    ulocs = uniform_locs
    w = window

    while app.state.running:
        if not windowed:
            _XSetInputFocus(display, w, RevertToParent, CurrentTime)

        x.XGetWindowAttributes(display, w, byref(wa))
        ww = wa.width
        wh = wa.height
        _glViewport(0, 0, ww, wh)

        # drain events
        while _XPending(display) > 0:
            _XNextEvent(display, byref(event))
            ev_type = event.type

            if ev_type == KeyPress:
                kp = cast(byref(event), POINTER(XKeyEvent))
                keysym = _XLookupKeysym(kp, 0)
                app._handle_keypress(keysym)
            elif ev_type == MotionNotify:
                mp = cast(byref(event), POINTER(XMotionEvent))
                app._handle_mousemove(mp, refresh_rate)
            elif ev_type == ButtonPress:
                bp = cast(byref(event), POINTER(XButtonEvent))
                app._handle_buttonpress(bp)
            elif ev_type == ButtonRelease:
                bp = cast(byref(event), POINTER(XButtonEvent))
                app._handle_buttonrelease(bp)
            elif ev_type == ClientMessage:
                if event.xclient.data.l[0] == wm_delete_window.value:
                    app.state.running = False

        app.camera_update(ww, wh)
        app.flashlight_update()

        # render
        cam = app.state.camera
        fl = app.state.flashlight
        m = app.state.mouse

        _glClearColor(0.1, 0.1, 0.1, 1.0)
        _glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
        _glUseProgram(program)

        _glUniform2f(ulocs["camera_pos"],      cam.position_x,     cam.position_y)
        _glUniform1f(ulocs["camera_scale"],     cam.scale)
        _glUniform2f(ulocs["window_size"],      float(ww),          float(wh))
        _glUniform2f(ulocs["screenshot_size"],  float(img.width),   float(img.height))
        _glUniform2f(ulocs["cursor_pos"],       m.curr_x,           m.curr_y)
        _glUniform1f(ulocs["fl_shadow"],        fl.shadow)
        _glUniform1f(ulocs["fl_radius"],        fl.radius)
        _glUniform1f(ulocs["fl_feather"],       app.config.feather)
        _glUniform1f(ulocs["mirror"],           1.0 if app.state.mirror else 0.0)

        _glBindTexture(GL_TEXTURE_2D, texture)
        _glBindVertexArray(vao)
        _glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_INT, None)

        _glXSwapBuffers(display, w)
        _glFinish()

    # cleanup
    if not windowed:
        x.XSetInputFocus(display, original_focus, RevertToParent, CurrentTime)
        x.XSync(display, False_)

    _libgl.glDeleteVertexArrays(1, byref(vao))
    _libgl.glDeleteBuffers(1, byref(vbo))
    _libgl.glDeleteBuffers(1, byref(ebo))
    _libgl.glDeleteProgram(program)
    _libgl.glDeleteTextures(1, byref(texture))

    _x11.XDestroyImage(img_ptr)
    _libgl.glXMakeCurrent(display, 0, None)
    _libgl.glXDestroyContext(display, gl_ctx)
    _x11.XDestroyWindow(display, window)
    _x11.XCloseDisplay(display)


if __name__ == "__main__":
    main()
